/* eslint-disable @typescript-eslint/no-unused-vars */
// (Do not edit directly)
// (Auto generated by the Cocokits 'generate-example-story-source')

import { AddonParametersSource, ThemeId } from '@cocokits/storybook-addon-theme';

export const SOURCE: AddonParametersSource[] = [
  {
    language: 'tsx',
    filename: 'LeadingWebsite.tsx',
    code: `

import { FormField, Input, Label, Leading } from '@cocokits/react-components';

export function LeadingWebsite() {
  return (
    <FormField>
      <Label>Website URL</Label>
      <Leading>https://</Leading>
      <Input/>
    </FormField>
  );
}
`,
  },
];
