/* eslint-disable */
// (Do not edit directly)
// (Auto generated by the Cocokits 'generate-example-story-source' on Mon Mar 24 2025

import { AddonParametersSource, ThemeId } from '@cocokits/storybook-addon-theme';

export const SOURCE: AddonParametersSource[] = [
  {
    language: 'tsx',
    filename: 'CheckboxLabelThrough.styled.tsx',
    code: `
import styled from 'styled-components';

const StrikedLabel = styled.span\`
  text-decoration: line-through;
\`;

export const Styled = {
  StrikedLabel,
};
`,
  },
  {
    language: 'tsx',
    filename: 'CheckboxLabelThrough.tsx',
    code: `
import { useState } from 'react';


import { Checkbox } from '@cocokits/react-checkbox';

import { Styled } from './CheckboxLabelThrough.styled';

export function CheckboxLabelThrough() {
  const [checked, setChecked] = useState(false);

  return (
    <Checkbox size='<%= size %>' value={1} checked={checked} onChange={() => setChecked((prev) => !prev)}>
      <Styled.StrikedLabel style={{ textDecoration: checked ? 'line-through' : 'none' }}>
        Checkbox Label
      </Styled.StrikedLabel>
    </Checkbox>
  );
}
`,
  },
];
