// (Do not edit directly)
// (Auto generated by the Cocokits 'generate-example-story-source' on Fri Feb 21 2025

import { AddonParametersSource, ThemeId } from '@cocokits/storybook-addon-theme';

export const SOURCE: AddonParametersSource[] = [
  {
    language: 'tsx',
    filename: 'EmailValidation.tsx',
    code: `

import { FormField, Label, Input, SvgIcon, Error } from '@cocokits/react-components';
import { useState } from 'react';
import { Icons } from '@cocokits/common-icons';

export function EmailValidation() {
  const [invalid, setInvalid] = useState(true);
  const [touched, setTouched] = useState(false);

  const onInput = (event: React.ChangeEvent<HTMLInputElement>) => {
    const value = event.currentTarget.value;
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    setInvalid(!emailRegex.test(value));
  };

  return (
    <FormField invalid={invalid}>
      <Label>Email</Label>
      <Input type="email" onInput={onInput} onBlur={(() => setTouched)(true)} />
      {
        invalid && touched && (
          <Error>
            <SvgIcon icon={Icons.warning} />
            <span>Enter a valid email address</span>
          </Error>
        )
      }
    </FormField>
  );
}
`,
  },
];
