/* eslint-disable max-lines */

/**
 * Do not edit directly
 * Generated by cocokits scssify-token executor on Fri Jun 21 2024 17:41:04 GMT+0200 (Central European Summer Time)
 */

export const colorThemeThemeA = {
  fill: {
    '50': 'colors-gray-50',
    '100': 'colors-gray-100',
    '200': 'colors-gray-200',
    '300': 'colors-gray-300',
    '400': 'colors-gray-400',
    '600': 'colors-gray-600',
    '00': 'colors-alpha-light-900',
  },
  state: {
    base: {
      background: 'colors-gray-50',
      border: 'colors-gray-200',
      disabled: 'colors-alpha-dark-200',
    },
    primary: {
      active: 'colors-blue-600',
      hover: 'colors-blue-500',
      selected: 'colors-blue-300',
    },
    destructive: {
      active: 'colors-red-600',
      hover: 'colors-red-400',
      selected: 'colors-red-300',
    },
    highlight: {
      active: 'colors-orange-400',
      hover: 'colors-orange-300',
      selected: 'colors-orange-200',
    },
    success: {
      active: 'colors-green-600',
      hover: 'colors-green-400',
      selected: 'colors-green-300',
    },
  },
};
