/* eslint-disable max-lines */

/**
 * Do not edit directly
 * Generated by cocokits scssify-token executor on Fri Jun 21 2024 17:41:04 GMT+0200 (Central European Summer Time)
 */

export const colorThemeThemeB = {
  fill: {
    '50': 'colors-bronze-50',
    '100': 'colors-bronze-100',
    '200': 'colors-bronze-200',
    '300': 'colors-bronze-300',
    '400': 'colors-bronze-400',
    '600': 'colors-bronze-600',
    '00': 'colors-alpha-light-900',
  },
  state: {
    base: {
      background: 'colors-bronze-50',
      border: 'colors-blue-gray-300',
      disabled: 'colors-alpha-dark-200',
    },
    primary: {
      active: 'colors-orange-600',
      hover: 'colors-orange-500',
      selected: 'colors-orange-400',
    },
    destructive: {
      active: 'colors-rose-600',
      hover: 'colors-rose-400',
      selected: 'colors-rose-300',
    },
    highlight: {
      active: 'colors-purple-500',
      hover: 'colors-purple-400',
      selected: 'colors-purple-200',
    },
    success: {
      active: 'colors-lime-600',
      hover: 'colors-lime-400',
      selected: 'colors-lime-300',
    },
  },
};
