/* eslint-disable max-lines */

/**
 * Do not edit directly
 * Generated by coco-kits scssify-token executor on Fri Jun 21 2024 17:41:04 GMT+0200 (Central European Summer Time)
 */

export const radiusDefault = {
  radi0: '0',
  radi1: '2px',
  radi2: '4px',
  radi3: '6px',
  radi4: '8px',
  radi5: '10px',
  radi6: '12px',
  radi7: '16px',
  radi8: '22px',
  radi9: '28px',
  radi10: '1000px',
};
