/* eslint-disable max-lines */

/**
 * Do not edit directly
 * Generated by coco-kits scssify-token executor on Fri Jun 21 2024 17:41:04 GMT+0200 (Central European Summer Time)
 */

export const radiusRounded = {
  radi0: '0',
  radi1: '4px',
  radi2: '6px',
  radi3: '8px',
  radi4: '10px',
  radi5: '16px',
  radi6: '20px',
  radi7: '28px',
  radi8: '32px',
  radi9: '40px',
  radi10: '2000px',
};
