/* eslint-disable max-lines */

/**
 * Do not edit directly
 * Generated by cocokits scssify-token executor on Fri Jun 21 2024 17:41:04 GMT+0200 (Central European Summer Time)
 */

export const sizingCompact = {
  spacing: {
    space0: '0',
    space1: '1px',
    space2: '2px',
    space3: '4px',
    space4: '6px',
    space5: '8px',
    space6: '10px',
    space7: '12px',
    space8: '16px',
    space9: '20px',
    space10: '24px',
    space11: '28px',
    space12: '32px',
    space13: '36px',
    space14: '40px',
    space15: '44px',
    space16: '48px',
    space17: '56px',
    space18: '64px',
    space19: '72px',
    space20: '80px',
    space21: '96px',
    space22: '112px',
    space23: '120px',
    space24: '128px',
    space25: '144px',
    space26: '160px',
    space27: '192px',
    space28: '208px',
    space29: '224px',
    space30: '256px',
    space31: '288px',
    space32: '320px',
    space33: '384px',
  },
  icon: {
    iconXs: '12px',
    iconSm: '16px',
    iconMd: '20px',
    iconLg: '24px',
    iconXl: '28px',
    icon2Xl: '32px',
    icon3Xl: '40px',
    icon4Xl: '44px',
  },
};
