/* eslint-disable max-lines */

/**
 * Do not edit directly
 * Generated by cocokits scssify-token executor on Fri Jun 21 2024 17:41:04 GMT+0200 (Central European Summer Time)
 */

export const sizingSpacious = {
  spacing: {
    space0: '0',
    space1: '2px',
    space2: '4px',
    space3: '8px',
    space4: '10px',
    space5: '12px',
    space6: '14px',
    space7: '16px',
    space8: '20px',
    space9: '24px',
    space10: '28px',
    space11: '32px',
    space12: '36px',
    space13: '40px',
    space14: '44px',
    space15: '48px',
    space16: '56px',
    space17: '64px',
    space18: '76px',
    space19: '88px',
    space20: '96px',
    space21: '112px',
    space22: '120px',
    space23: '128px',
    space24: '144px',
    space25: '160px',
    space26: '192px',
    space27: '208px',
    space28: '224px',
    space29: '256px',
    space30: '288px',
    space31: '320px',
    space32: '384px',
    space33: '420px',
  },
  icon: {
    iconXs: '14px',
    iconSm: '18px',
    iconMd: '22px',
    iconLg: '26px',
    iconXl: '30px',
    icon2Xl: '34px',
    icon3Xl: '42px',
    icon4Xl: '46px',
  },
};
