/* eslint-disable */
// (Do not edit directly)
// (Auto generated by the Cocokits 'generate-example-story-source')

import { AddonParametersSource, ThemeId } from '@cocokits/storybook-addon-theme';

export const SOURCE: AddonParametersSource[] = [
  {
    language: 'angular-ts',
    filename: 'checkbox-group-column.component.ts',
    code: `
import { Component, input } from '@angular/core';

import { CheckboxComponent } from '@cocokits/angular-components';


@Component({
  selector: 'cck-checkbox-group-column',
  imports: [CheckboxComponent],
  template: \`
    <div class="checkbox-group-column">
      <span class="label">My hobbies</span>
      <cck-checkbox [size]="'<%=size%>'" [value]="1">Comic books</cck-checkbox>
      <cck-checkbox [size]="'<%=size%>'" [value]="2">Listen to music</cck-checkbox>
      <cck-checkbox [size]="'<%=size%>'" [value]="3">Travel the world</cck-checkbox>
      <cck-checkbox [size]="'<%=size%>'" [value]="4">Watch movies</cck-checkbox>
    </div>
  \`,
  styles: \`
    .checkbox-group-column {
      display: flex;
      flex-direction: column;
      gap: 12px;
    }

    .label {
      color: var(--checkbox-group-column-color);
      font-style: italic;
    }
  \`,
})
export class CheckboxGroupColumnComponent {

}
`,
  },
  {
    language: 'scss',
    filename: 'global.scss',
    code: `
      :root {--checkbox-group-column-color: var(--color-palette-gray-800);
        --checkbox-group-column-font-family: Inter;
      }`,
    visibleConditions: [(theme) => theme.id === ThemeId.CocoKits],
  },
  {
    language: 'scss',
    filename: 'global.scss',
    code: `
      :root {--checkbox-group-column-color: var(--colors-gray-300);
        --checkbox-group-column-font-family: var(--font-family);
      }`,
    visibleConditions: [(theme) => theme.id === ThemeId.FramesX],
  },
];
