// (Do not edit directly)
// (Auto generated by the Cocokits 'generate-example-story-source' on Wed Mar 05 2025

import { AddonParametersSource, ThemeId } from '@cocokits/storybook-addon-theme';

export const SOURCE: AddonParametersSource[] = [
  {
    language: 'angular-ts',
    filename: 'social-buttons.component.ts',
    code: `
import { Component, input } from '@angular/core';

import { IconButtonComponent } from '@cocokits/angular-button';
import { SvgIconComponent } from '@cocokits/angular-icon';
import { Icons } from '@cocokits/common-icons';


@Component({
  standalone: true,
  selector: 'cck-social-buttons',
  imports: [IconButtonComponent, SvgIconComponent],
  template: \`
    <button cck-icon-button [color]="'<%=color%>'" [type]="'<%=type%>'" [size]="'<%=size%>'">
      <cck-svg-icon [icon]="Icons.x" [size]="'<%=iconSize%>'"/>
    </button>

    <button cck-icon-button [color]="'<%=color%>'" [type]="'<%=type%>'" [size]="'<%=size%>'">
      <cck-svg-icon [icon]="Icons.github" [size]="'<%=iconSize%>'"/>
    </button>

    <button cck-icon-button [color]="'<%=color%>'" [type]="'<%=type%>'" [size]="'<%=size%>'">
      <cck-svg-icon [icon]="Icons.instagram" [size]="'<%=iconSize%>'"/>
    </button>
  \`,
  styles: \`
    :host {
      display: flex;
      gap: 8px;
    }
  \`,
})
export class SocialButtonsComponent {

  protected readonly Icons = Icons;
}
`,
  },
];
