/* eslint-disable max-lines */

/**
 * Do not edit directly
 * Generated by cocokits scssify-token executor on Thu Jun 20 2024 21:48:21 GMT+0200 (Central European Summer Time)
 */

export const brandColor1 = {
  color: {
    brand: {
      light: 'var(--color-brand-light)',
      default: 'var(--color-brand-default)',
      dark: 'var(--color-brand-dark)',
    },
    info: {
      light: 'var(--color-info-light)',
      default: 'var(--color-info-default)',
      dark: 'var(--color-info-dark)',
    },
    warning: {
      light: 'var(--color-warning-light)',
      default: 'var(--color-warning-default)',
      dark: 'var(--color-warning-dark)',
    },
    error: {
      light: 'var(--color-error-light)',
      default: 'var(--color-error-default)',
      dark: 'var(--color-error-dark)',
    },
    hContrast: {
      light: 'var(--color-h-contrast-light)',
      default: 'var(--color-h-contrast-default)',
      dark: 'var(--color-h-contrast-dark)',
    },
    mContrast: {
      light: 'var(--color-m-contrast-light)',
      default: 'var(--color-m-contrast-default)',
      dark: 'var(--color-m-contrast-dark)',
    },
    lContrast: {
      light: 'var(--color-l-contrast-light)',
      default: 'var(--color-l-contrast-default)',
      dark: 'var(--color-l-contrast-dark)',
    },
    body: {
      background: 'var(--color-body-background)',
    },
  },
};
