/* eslint-disable max-lines */

/**
 * Do not edit directly
 * Generated by cocokits scssify-token executor on Sat Jul 20 2024 22:23:15 GMT+0200 (Central European Summer Time)
 */

export const components = {
  icon: {
    size: {
      default: 'var(--icon-size-default)',
      xs: 'var(--icon-size-xs)',
      sm: 'var(--icon-size-sm)',
      md: 'var(--icon-size-md)',
      lg: 'var(--icon-size-lg)',
      xl: 'var(--icon-size-xl)',
      '2Xl': 'var(--icon-size-2xl)',
    },
  },
  button: {
    primary: {
      height: {
        sm: 'var(--button-primary-height-sm)',
        md: 'var(--button-primary-height-md)',
        lg: 'var(--button-primary-height-lg)',
      },
      radius: 'var(--button-primary-radius)',
      border: {
        default: 'var(--button-primary-border-default)',
      },
    },
  },
  checkbox: {
    color: {
      checkmark: 'var(--checkbox-color-checkmark)',
    },
    size: {
      sm: 'var(--checkbox-size-sm)',
      md: 'var(--checkbox-size-md)',
      lg: 'var(--checkbox-size-lg)',
    },
  },
  radio: {
    paddingInput: {
      sm: 'var(--radio-padding-input-sm)',
      md: 'var(--radio-padding-input-md)',
      lg: 'var(--radio-padding-input-lg)',
    },
    size: {
      sm: 'var(--radio-size-sm)',
      md: 'var(--radio-size-md)',
      lg: 'var(--radio-size-lg)',
    },
  },
};
