/* eslint-disable max-lines */

/**
 * Do not edit directly
 * Generated by cocokits scssify-token executor on Fri Jul 05 2024 16:30:59 GMT+0200 (Central European Summer Time)
 */

export const components = {
  icon: {
    size: {
      default: 'var(--icon-size-default)',
      xs: 'var(--icon-size-xs)',
      sm: 'var(--icon-size-sm)',
      md: 'var(--icon-size-md)',
      lg: 'var(--icon-size-lg)',
      xl: 'var(--icon-size-xl)',
      '2Xl': 'var(--icon-size-2xl)',
    },
  },
  button: {
    primary: {
      height: {
        sm: 'var(--button-primary-height-sm)',
        md: 'var(--button-primary-height-md)',
        lg: 'var(--button-primary-height-lg)',
      },
      radius: 'var(--button-primary-radius)',
      border: {
        default: 'var(--button-primary-border-default)',
      },
    },
  },
};
