/* eslint-disable max-lines */

/**
 * Do not edit directly
 * Generated by coco-kits scssify-token executor on Thu Jun 20 2024 21:48:21 GMT+0200 (Central European Summer Time)
 */

export const componentsSize = {
  size: {
    icon: {
      default: 'var(--size-icon-default)',
      xs: 'var(--size-icon-xs)',
      sm: 'var(--size-icon-sm)',
      md: 'var(--size-icon-md)',
      lg: 'var(--size-icon-lg)',
      xl: 'var(--size-icon-xl)',
      '2Xl': 'var(--size-icon-2xl)',
    },
  },
};
