/**
 * Do not edit directly
 * Generated by coco-kits scssify-token executor on Thu Jun 13 2024 23:59:37 GMT+0200 (Central European Summer Time)
 */

export const localStyle = {
  display2Xl: {
    regular: 'var(--display-2xl-regular',
    medium: 'var(--display-2xl-medium',
    semibold: 'var(--display-2xl-semibold',
    bold: 'var(--display-2xl-bold',
    light: 'var(--display-2xl-light',
  },
  displayXl: {
    bold: 'var(--display-xl-bold',
    semibold: 'var(--display-xl-semibold',
    medium: 'var(--display-xl-medium',
    regular: 'var(--display-xl-regular',
    light: 'var(--display-xl-light',
  },
  displayLg: {
    light: 'var(--display-lg-light',
    regular: 'var(--display-lg-regular',
    medium: 'var(--display-lg-medium',
    semibold: 'var(--display-lg-semibold',
    bold: 'var(--display-lg-bold',
  },
  displayMd: {
    light: 'var(--display-md-light',
    regular: 'var(--display-md-regular',
    medium: 'var(--display-md-medium',
    semibold: 'var(--display-md-semibold',
    bold: 'var(--display-md-bold',
  },
  displaySm: {
    bold: 'var(--display-sm-bold',
    semibold: 'var(--display-sm-semibold',
    medium: 'var(--display-sm-medium',
    regular: 'var(--display-sm-regular',
    light: 'var(--display-sm-light',
  },
  displayXs: {
    light: 'var(--display-xs-light',
    regular: 'var(--display-xs-regular',
    medium: 'var(--display-xs-medium',
    semibold: 'var(--display-xs-semibold',
    bold: 'var(--display-xs-bold',
  },
  textXl: {
    bold: 'var(--text-xl-bold',
    semibold: 'var(--text-xl-semibold',
    medium: 'var(--text-xl-medium',
    regular: 'var(--text-xl-regular',
    light: 'var(--text-xl-light',
  },
  textLg: {
    light: 'var(--text-lg-light',
    regular: 'var(--text-lg-regular',
    medium: 'var(--text-lg-medium',
    semibold: 'var(--text-lg-semibold',
    bold: 'var(--text-lg-bold',
  },
  textMd: {
    bold: 'var(--text-md-bold',
    semibold: 'var(--text-md-semibold',
    medium: 'var(--text-md-medium',
    regular: 'var(--text-md-regular',
    light: 'var(--text-md-light',
  },
  textSm: {
    light: 'var(--text-sm-light',
    regular: 'var(--text-sm-regular',
    medium: 'var(--text-sm-medium',
    semibold: 'var(--text-sm-semibold',
    bold: 'var(--text-sm-bold',
  },
  textXs: {
    bold: 'var(--text-xs-bold',
    semibold: 'var(--text-xs-semibold',
    medium: 'var(--text-xs-medium',
    regular: 'var(--text-xs-regular',
    light: 'var(--text-xs-light',
  },
};
