/* eslint-disable max-lines */

/**
 * Do not edit directly
 * Generated by cocokits scssify-token executor on Fri Jul 05 2024 16:30:59 GMT+0200 (Central European Summer Time)
 */

export const localStyle = {
  display2Xl: {
    light: 'var(--display-2xl-light)',
    regular: 'var(--display-2xl-regular)',
    medium: 'var(--display-2xl-medium)',
    semibold: 'var(--display-2xl-semibold)',
    bold: 'var(--display-2xl-bold)',
  },
  displayXl: {
    light: 'var(--display-xl-light)',
    regular: 'var(--display-xl-regular)',
    medium: 'var(--display-xl-medium)',
    semibold: 'var(--display-xl-semibold)',
    bold: 'var(--display-xl-bold)',
  },
  displayLg: {
    light: 'var(--display-lg-light)',
    regular: 'var(--display-lg-regular)',
    medium: 'var(--display-lg-medium)',
    semibold: 'var(--display-lg-semibold)',
    bold: 'var(--display-lg-bold)',
  },
  displayMd: {
    light: 'var(--display-md-light)',
    regular: 'var(--display-md-regular)',
    medium: 'var(--display-md-medium)',
    semibold: 'var(--display-md-semibold)',
    bold: 'var(--display-md-bold)',
  },
  displaySm: {
    light: 'var(--display-sm-light)',
    regular: 'var(--display-sm-regular)',
    medium: 'var(--display-sm-medium)',
    semibold: 'var(--display-sm-semibold)',
    bold: 'var(--display-sm-bold)',
  },
  displayXs: {
    light: 'var(--display-xs-light)',
    regular: 'var(--display-xs-regular)',
    medium: 'var(--display-xs-medium)',
    semibold: 'var(--display-xs-semibold)',
    bold: 'var(--display-xs-bold)',
  },
  textXl: {
    light: 'var(--text-xl-light)',
    regular: 'var(--text-xl-regular)',
    medium: 'var(--text-xl-medium)',
    semibold: 'var(--text-xl-semibold)',
    bold: 'var(--text-xl-bold)',
  },
  textLg: {
    light: 'var(--text-lg-light)',
    regular: 'var(--text-lg-regular)',
    medium: 'var(--text-lg-medium)',
    semibold: 'var(--text-lg-semibold)',
    bold: 'var(--text-lg-bold)',
  },
  textMd: {
    light: 'var(--text-md-light)',
    regular: 'var(--text-md-regular)',
    medium: 'var(--text-md-medium)',
    semibold: 'var(--text-md-semibold)',
    bold: 'var(--text-md-bold)',
  },
  textSm: {
    light: 'var(--text-sm-light)',
    regular: 'var(--text-sm-regular)',
    medium: 'var(--text-sm-medium)',
    semibold: 'var(--text-sm-semibold)',
    bold: 'var(--text-sm-bold)',
  },
  textXs: {
    light: 'var(--text-xs-light)',
    regular: 'var(--text-xs-regular)',
    medium: 'var(--text-xs-medium)',
    semibold: 'var(--text-xs-semibold)',
    bold: 'var(--text-xs-bold)',
  },
};
