/* eslint-disable max-lines */

/**
 * Do not edit directly
 * Generated by coco-kits scssify-token executor on Thu Jun 20 2024 22:33:35 GMT+0200 (Central European Summer Time)
 */

export const themeDark = {
  color: {
    bg: {
      body: {
        alpha: {
          '0': '#05030d00',
          '1': '#05030d05',
          '2': '#05030d0a',
          '3': '#05030d0f',
          '4': '#05030d14',
          '5': '#05030d1a',
          '6': '#05030d33',
          '7': '#05030d66',
          '8': '#05030d99',
          '9': '#05030dcc',
          '10': '#05030d',
        },
      },
      bodyInverse: {
        alpha: {
          '0': '#ffffff00',
          '1': '#ffffff05',
          '2': '#ffffff0a',
          '3': '#ffffff0f',
          '4': '#ffffff14',
          '5': '#ffffff1a',
          '6': '#ffffff33',
          '7': '#ffffff66',
          '8': '#ffffff99',
          '9': '#ffffffcc',
          '10': '#ffffff',
        },
      },
      button: {
        primary: '#1bbf8233',
        primaryHover: '#1bbf8266',
      },
      table: {
        even: '#ffffff0f',
      },
      overlay: {
        backdrop: '#ffffff33',
        shadow1: '#000c1d05',
        shadow2: '#000c1d05',
        surface: '#05030d',
      },
      card: {
        surface: '#ffffff0f',
      },
    },
    brand: {
      alpha0: '#1bbf8205',
      alpha1: '#1bbf820a',
      alpha2: '#1bbf820f',
      alpha3: '#1bbf8214',
      alpha4: '#1bbf821a',
      alpha5: '#1bbf8233',
      alpha6: '#1bbf8266',
      alpha7: '#1bbf8299',
      alpha8: '#1bbf82cc',
      alpha9: '#1bbf82e5',
      alpha10: '#1bbf82',
      default: '#1bbf82',
    },
    font: {
      contrast1: '#ffffff66',
      contrast2: '#ffffff99',
      contrast3: '#ffffffcc',
      contrast4: '#ffffff',
    },
    border: {
      card: {
        default: '#ffffff1a',
      },
      alpha: {
        '0': '#ffffff00',
        '1': '#ffffff05',
        '2': '#ffffff0a',
        '3': '#ffffff0f',
        '4': '#ffffff14',
        '5': '#ffffff1a',
        '6': '#ffffff33',
        '7': '#ffffff66',
        '8': '#ffffff99',
        '9': '#ffffffcc',
        '10': '#ffffff',
        default: '#ffffff1a',
      },
      button: {
        primary: '#1bbf8266',
        primaryHover: '#1bbf82e5',
      },
    },
  },
};
