/* eslint-disable max-lines */

/**
 * Do not edit directly
 * Generated by cocokits scssify-token executor on Thu Jun 20 2024 22:33:35 GMT+0200 (Central European Summer Time)
 */

export const themeLight = {
  color: {
    bg: {
      body: {
        alpha: {
          '0': '#ffffff00',
          '1': '#ffffff05',
          '2': '#ffffff0a',
          '3': '#ffffff0f',
          '4': '#ffffff14',
          '5': '#ffffff1a',
          '6': '#ffffff33',
          '7': '#ffffff66',
          '8': '#ffffff99',
          '9': '#ffffffcc',
          '10': '#ffffff',
        },
      },
      bodyInverse: {
        alpha: {
          '0': '#000c1d00',
          '1': '#000c1d05',
          '2': '#000c1d0a',
          '3': '#000c1d0f',
          '4': '#000c1d14',
          '5': '#000c1d1a',
          '6': '#000c1d33',
          '7': '#000c1d66',
          '8': '#000c1d99',
          '9': '#000c1dcc',
          '10': '#000c1d',
        },
      },
      button: {
        primary: '#129c6933',
        primaryHover: '#129c6966',
      },
      table: {
        even: '#000c1d05',
      },
      overlay: {
        backdrop: '#ffffff33',
        shadow1: '#000c1d1a',
        shadow2: '#000c1d14',
        surface: '#ffffff',
      },
      card: {
        surface: '#000c1d05',
      },
    },
    brand: {
      alpha0: '#129c6905',
      alpha1: '#129c690a',
      alpha2: '#129c690f',
      alpha3: '#129c6914',
      alpha4: '#129c691a',
      alpha5: '#129c6933',
      alpha6: '#129c6966',
      alpha7: '#129c6999',
      alpha8: '#129c69cc',
      alpha9: '#129c69e5',
      alpha10: '#129c69',
      default: '#129c69',
    },
    font: {
      contrast1: '#000c1d66',
      contrast2: '#000c1d99',
      contrast3: '#000c1dcc',
      contrast4: '#000c1d',
    },
    border: {
      card: {
        default: '#000c1d14',
      },
      alpha: {
        '0': '#000c1d00',
        '1': '#000c1d05',
        '2': '#000c1d0a',
        '3': '#000c1d0f',
        '4': '#000c1d14',
        '5': '#000c1d1a',
        '6': '#000c1d33',
        '7': '#000c1d66',
        '8': '#000c1d99',
        '9': '#000c1dcc',
        '10': '#000c1d',
        default: '#000c1d1a',
      },
      button: {
        primary: '#129c6966',
        primaryHover: '#129c69e5',
      },
    },
  },
};
