// (Do not edit directly)
// (Auto generated by the Cocokits 'generate-example-story-source' on Thu Mar 27 2025

import { AddonParametersSource, ThemeId } from '@cocokits/storybook-addon-theme';

export const SOURCE: AddonParametersSource[] = [
  {
    language: 'angular-ts',
    filename: 'checkbox-group-row.component.ts',
    code: `
import { Component, input } from '@angular/core';

import { CheckboxComponent } from '@cocokits/angular-checkbox';


@Component({
  standalone: true,
  selector: 'cck-checkbox-group-row',
  imports: [CheckboxComponent],
  template: \`
  <div>
    <i style="color: var(--checkbox-group-column-color);">Favorite food</i>
      <div style="display: flex; flex-direction: row; gap: 12px; marginTop: 10px;">
      <cck-checkbox [size]="'<%=size%>'" [value]="1">Pizza</cck-checkbox>
      <cck-checkbox [size]="'<%=size%>'" [value]="1">Pasta</cck-checkbox>
      <cck-checkbox [size]="'<%=size%>'" [value]="1">Fruits</cck-checkbox>
    </div>
  </div>
  \`,
  styles: \`\`,
})
export class CheckboxGroupRowComponent {

}
`,
  },
  {
    language: 'scss',
    filename: 'global.scss',
    code: `
      :root {--checkbox-group-column-color: var(--color-palette-gray-800);
      }`,
    visibleConditions: [(theme) => theme.id === ThemeId.CocoKits],
  },
  {
    language: 'scss',
    filename: 'global.scss',
    code: `
      :root {--checkbox-group-column-color: var(--colors-gray-300);
      }`,
    visibleConditions: [(theme) => theme.id === ThemeId.FramesX],
  },
];
