/* eslint-disable */
// (Do not edit directly)
// (Auto generated by the Cocokits 'generate-example-story-source')

import { AddonParametersSource, ThemeId } from '@cocokits/storybook-addon-theme';

export const SOURCE: AddonParametersSource[] = [
  {
    language: 'angular-ts',
    filename: 'checkbox-group-row.component.ts',
    code: `
import { Component, input } from '@angular/core';

import { CheckboxComponent } from '@cocokits/angular-components';


@Component({
  standalone: true,
  selector: 'cck-checkbox-group-row',
  imports: [CheckboxComponent],
  template: \`
    <div class="checkbox-group-row-wrapper">
      <span class="label">Favorite food</span>
      <div class="checkbox-group-row">
        <cck-checkbox [size]="'<%=size%>'" [value]="1">Pizza</cck-checkbox>
        <cck-checkbox [size]="'<%=size%>'" [value]="2">Pasta</cck-checkbox>
        <cck-checkbox [size]="'<%=size%>'" [value]="3">Fruits</cck-checkbox>
      </div>
    </div>
  \`,
  styles: \`
    .checkbox-group-row-wrapper {
      display: flex;
      flex-direction: column;
    }

    .label {
      color: var(--checkbox-group-column-color);
      font-style: italic;
    }

    .checkbox-group-row {
      display: flex;
      flex-direction: row;
      gap: 12px;
      margin-top: 10px;
    }
  \`,
})
export class CheckboxGroupRowComponent {

}
`,
  },
  {
    language: 'scss',
    filename: 'global.scss',
    code: `
      :root {--checkbox-group-column-color: var(--color-palette-gray-800);
        --checkbox-group-column-font-family: Inter;
      }`,
    visibleConditions: [(theme) => theme.id === ThemeId.CocoKits],
  },
  {
    language: 'scss',
    filename: 'global.scss',
    code: `
      :root {--checkbox-group-column-color: var(--colors-gray-300);
        --checkbox-group-column-font-family: var(--font-family);
      }`,
    visibleConditions: [(theme) => theme.id === ThemeId.FramesX],
  },
];
