/* eslint-disable max-lines */

/**
 * Do not edit directly
 * Generated by cocokits scssify-token executor on Thu Jun 20 2024 21:48:21 GMT+0200 (Central European Summer Time)
 */

export const brandColor1Light = {
  color: {
    brand: {
      light: 'color-palette-phlox-600',
      default: 'color-palette-phlox-700',
      dark: 'color-palette-phlox-900',
    },
    info: {
      light: 'color-palette-blue-400',
      default: 'color-palette-blue-500',
      dark: 'color-palette-blue-800',
    },
    warning: {
      light: 'color-palette-orange-peel-300',
      default: 'color-palette-orange-peel-500',
      dark: 'color-palette-orange-peel-600',
    },
    error: {
      light: 'color-palette-imperial-red-400',
      default: 'color-palette-imperial-red-500',
      dark: 'color-palette-imperial-red-600',
    },
    hContrast: {
      light: 'color-palette-black-50',
      default: 'color-palette-black-200',
      dark: 'color-palette-black-400',
    },
    mContrast: {
      light: 'color-palette-gray-300',
      default: 'color-palette-gray-500',
      dark: 'color-palette-gray-700',
    },
    lContrast: {
      light: 'color-palette-white-50',
      default: 'color-palette-white-200',
      dark: 'color-palette-white-400',
    },
    body: {
      background: 'color-palette-white-50',
    },
  },
};
