/* eslint-disable max-lines */

/**
 * Do not edit directly
 * Generated by coco-kits scssify-token executor on Thu Jun 20 2024 21:48:21 GMT+0200 (Central European Summer Time)
 */

export const componentsSizeDefault = {
  size: {
    icon: {
      default: 'size-icon-xs',
      xs: 'size-16',
      sm: 'size-20',
      md: 'size-24',
      lg: 'size-28',
      xl: 'size-32',
      '2Xl': 'size-48',
    },
  },
};
