/* eslint-disable max-lines */

/**
 * Do not edit directly
 * Generated by cocokits scssify-token executor on Sat Jul 20 2024 22:23:15 GMT+0200 (Central European Summer Time)
 */

export const componentsDefault = {
  icon: {
    size: {
      default: 'icon-size-xs',
      xs: 'size-16',
      sm: 'size-20',
      md: 'size-24',
      lg: 'size-28',
      xl: 'size-32',
      '2Xl': 'size-48',
    },
  },
  button: {
    primary: {
      height: {
        sm: 'size-28',
        md: 'size-32',
        lg: 'size-40',
      },
      radius: 'size-4',
      border: {
        default: '#ffffff',
      },
    },
  },
  checkbox: {
    color: {
      checkmark: 'color-palette-white-50',
    },
    size: {
      sm: 'size-16',
      md: 'size-20',
      lg: 'size-24',
    },
  },
  radio: {
    paddingInput: {
      sm: 'size-4',
      md: 'size-8',
      lg: 'size-12',
    },
    size: {
      sm: 'size-16',
      md: 'size-20',
      lg: 'size-24',
    },
  },
};
