/* eslint-disable max-lines */

/**
 * Do not edit directly
 * Generated by cocokits scssify-token executor on Fri Jul 05 2024 16:30:59 GMT+0200 (Central European Summer Time)
 */

export const componentsDefault = {
  icon: {
    size: {
      default: 'icon-size-xs',
      xs: 'size-16',
      sm: 'size-20',
      md: 'size-24',
      lg: 'size-28',
      xl: 'size-32',
      '2Xl': 'size-48',
    },
  },
  button: {
    primary: {
      height: {
        sm: 'size-28',
        md: 'size-32',
        lg: 'size-40',
      },
      radius: 'size-4',
      border: {
        default: '#ffffff',
      },
    },
  },
};
