/**
 * Do not edit directly
 * Generated by coco-kits scssify-token executor on Wed Jun 19 2024 16:01:42 GMT+0200 (Central European Summer Time)
 */

export const localStyleDefault = {
  display2Xl: {
    regular: '400 72px / 90px Inter',
    medium: '500 72px / 90px Inter',
    semibold: '700 72px / 90px Inter',
    bold: '700 72px / 90px Inter',
    light: '300 72px / 90px Inter',
  },
  displayXl: {
    bold: '700 60px / 72px Inter',
    semibold: '700 60px / 72px Inter',
    medium: '500 60px / 72px Inter',
    regular: '400 60px / 72px Inter',
    light: '300 60px / 72px Inter',
  },
  displayLg: {
    light: '300 48px / 60px Inter',
    regular: '400 48px / 60px Inter',
    medium: '500 48px / 60px Inter',
    semibold: '700 48px / 60px Inter',
    bold: '700 48px / 60px Inter',
  },
  displayMd: {
    light: '300 36px / 44px Inter',
    regular: '400 36px / 44px Inter',
    medium: '500 36px / 44px Inter',
    semibold: '700 36px / 44px Inter',
    bold: '700 36px / 44px Inter',
  },
  displaySm: {
    bold: '700 30px / 38px Inter',
    semibold: '700 30px / 38px Inter',
    medium: '500 30px / 38px Inter',
    regular: '400 30px / 38px Inter',
    light: '300 30px / 38px Inter',
  },
  displayXs: {
    light: '300 24px / 32px Inter',
    regular: '400 24px / 32px Inter',
    medium: '500 24px / 32px Inter',
    semibold: '700 24px / 32px Inter',
    bold: '700 24px / 32px Inter',
  },
  textXl: {
    bold: '700 20px / 30px Inter',
    semibold: '700 20px / 30px Inter',
    medium: '500 20px / 30px Inter',
    regular: '400 20px / 30px Inter',
    light: '300 20px / 30px Inter',
  },
  textLg: {
    light: '300 18px / 28px Inter',
    regular: '400 18px / 28px Inter',
    medium: '500 18px / 28px Inter',
    semibold: '700 18px / 28px Inter',
    bold: '700 18px / 28px Inter',
  },
  textMd: {
    bold: '700 16px / 24px Inter',
    semibold: '700 16px / 24px Inter',
    medium: '500 16px / 24px Inter',
    regular: '400 16px / 24px Inter',
    light: '300 16px / 24px Inter',
  },
  textSm: {
    light: '300 14px / 20px Inter',
    regular: '400 14px / 20px Inter',
    medium: '500 14px / 20px Inter',
    semibold: '700 14px / 20px Inter',
    bold: '700 14px / 20px Inter',
  },
  textXs: {
    bold: '700 12px / 18px Inter',
    semibold: '700 12px / 18px Inter',
    medium: '500 12px / 18px Inter',
    regular: '400 12px / 18px Inter',
    light: '300 12px / 18px Inter',
  },
};
