/* eslint-disable */
// (Do not edit directly)
// (Auto generated by the Cocokits 'generate-example-story-source')

import { AddonParametersSource, ThemeId } from '@cocokits/storybook-addon-theme';

export const SOURCE: AddonParametersSource[] = [
  {
    language: 'tsx',
    filename: 'TextareaMaxChar.tsx',
    code: `
import { useState } from 'react';


import { FormField, Hint, Label, Textarea } from '@cocokits/react-form-field';

export function TextareaMaxChar() {
  const [valueLength, setValueLength] = useState(0);
  const maxLength = 150;

  return (
    <FormField>
      <Label>Description</Label>
      <Textarea 
        maxLength={maxLength}
        placeholder="Short project description"
        onChange={e => setValueLength(e.target.value.length)}/>
      <Hint>{valueLength}/{maxLength} characters max</Hint>
    </FormField>
  );
}
`,
  },
];
