// (Do not edit directly)
// (Auto generated by the Cocokits 'generate-example-story-source' on Thu Mar 27 2025

import { AddonParametersSource, ThemeId } from '@cocokits/storybook-addon-theme';

export const SOURCE: AddonParametersSource[] = [
  {
    language: 'tsx',
    filename: 'CheckboxGroupRow.tsx',
    code: `

import { Checkbox } from '@cocokits/react-checkbox';

export function CheckboxGroupRow() {
  return (
    <div>
      <i style={{ color: 'var(--checkbox-group-column-color)' }}>Favorite food</i>
      <div style={{ display: 'flex', flexDirection: 'row', gap: '12px', marginTop: '10px' }}>
        <Checkbox size='<%= size %>' value={1}>
          Pizza
        </Checkbox>
        <Checkbox size='<%= size %>' value={1}>
          Pasta
        </Checkbox>
        <Checkbox size='<%= size %>' value={1}>
          Fruits
        </Checkbox>
      </div>
    </div>
  );
}
`,
  },
  {
    language: 'scss',
    filename: 'global.scss',
    code: `
      :root {--checkbox-group-column-color: var(--color-palette-gray-800);
      }`,
    visibleConditions: [(theme) => theme.id === ThemeId.CocoKits],
  },
  {
    language: 'scss',
    filename: 'global.scss',
    code: `
      :root {--checkbox-group-column-color: var(--colors-gray-300);
      }`,
    visibleConditions: [(theme) => theme.id === ThemeId.FramesX],
  },
];
