/* eslint-disable max-lines */

/**
 * Do not edit directly
 * Generated by cocokits scssify-token executor on Fri Jun 21 2024 17:41:04 GMT+0200 (Central European Summer Time)
 */

export const collections = {
  'local-style': ['default'],
  sizing: ['compact', 'spacious'],
  'color-theme': ['theme-a', 'theme-b'],
  'color-mode': ['light', 'dark'],
  radius: ['default', 'rounded'],
  typography: ['font-a'],
};
