/* eslint-disable */
// (Do not edit directly)
// (Auto generated by the Cocokits 'generate-example-story-source')

import { AddonParametersSource, ThemeId } from '@cocokits/storybook-addon-theme';

export const SOURCE: AddonParametersSource[] = [
  {
    language: 'html',
    filename: 'checkbox-box-selection.component.html',
    code: `
<cck-checkbox class="checkbox__box" [value]="1">
    Vegetarian
</cck-checkbox>
<cck-checkbox class="checkbox__box" [value]="2">
    Gluten-Free
</cck-checkbox>`,
  },
  {
    language: 'scss',
    filename: 'checkbox-box-selection.component.scss',
    code: `
:host {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.checkbox__box {
  padding: var(--cck-checkbox-padding);
  border: var(--cck-checkbox-border-width) var(--cck-checkbox-border-style) var(--cck-checkbox-border-color);
  border-radius: var(--cck-checkbox-border-radius);
}
`,
  },
  {
    language: 'angular-ts',
    filename: 'checkbox-box-selection.component.ts',
    code: `
import { Component, input } from '@angular/core';

import { CheckboxComponent } from '@cocokits/angular-components';


@Component({
  standalone: true,
  selector: 'cck-checkbox-box-selection',
  imports: [CheckboxComponent],
  templateUrl: './checkbox-box-selection.component.html',
  styleUrls: ['./checkbox-box-selection.component.scss'],
})
export class CheckboxBoxSelectionComponent {

}
`,
  },
  {
    language: 'scss',
    filename: 'global.scss',
    code: `
      :root {--cck-checkbox-border-color: var(--color-disabled-surface);
        --cck-checkbox-border-width: 1px;
        --cck-checkbox-border-style: solid;
        --cck-checkbox-border-radius: 12px;
        --cck-checkbox-padding: 16px;
        --cck-checkbox-gap: var(--toggle-spacing-gap);
      }`,
    visibleConditions: [(theme) => theme.id === ThemeId.CocoKits],
  },
  {
    language: 'scss',
    filename: 'global.scss',
    code: `
      :root {--cck-checkbox-border-color: var(--base-border);
        --cck-checkbox-border-width: var(--spacing-1);
        --cck-checkbox-border-style: solid;
        --cck-checkbox-border-radius: var(--radi-6);
        --cck-checkbox-padding: var(--spacing-8);
        --cck-checkbox-gap: var(--spacing-7);
      }`,
    visibleConditions: [(theme) => theme.id === ThemeId.FramesX],
  },
];
