/* eslint-disable */
// (Do not edit directly)
// (Auto generated by the Cocokits 'generate-example-story-source')

import { AddonParametersSource, ThemeId } from '@cocokits/storybook-addon-theme';

export const SOURCE: AddonParametersSource[] = [
  {
    language: 'html',
    filename: 'checkbox-box-selection-info.component.html',
    code: `
<div class="checkbox__box">
    <cck-checkbox [value]="1">
        Leave at Door
    </cck-checkbox>
    <cck-svg-icon [icon]='Icons.info' [size]="'<%=IconSize%>'" />
</div>
<div class="checkbox__box">
    <cck-checkbox [value]="2">
        Call on Arrival
    </cck-checkbox>
    <cck-svg-icon [icon]='Icons.info' [size]="'<%=IconSize%>'" />
</div>`,
  },
  {
    language: 'scss',
    filename: 'checkbox-box-selection-info.component.scss',
    code: `
:host {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.checkbox__box {
  padding: var(--cck-checkbox-padding);
  border: var(--cck-checkbox-border-width) var(--cck-checkbox-border-style) var(--cck-checkbox-border-color);
  border-radius: var(--cck-checkbox-border-radius);
  direction: rtl;
  display: flex;
  align-items: center;
  gap: var(--cck-checkbox-box-gap);

  svg {
    fill: var(--cck-checkbox-icon-color);
  }
}
`,
  },
  {
    language: 'angular-ts',
    filename: 'checkbox-box-selection-info.component.ts',
    code: `
import { Component, input } from '@angular/core';

import { CheckboxComponent, SvgIconComponent } from '@cocokits/angular-components';
import { Icons } from '@cocokits/common-icons';


@Component({
  standalone: true,
  selector: 'cck-checkbox-box-selection-info',
  imports: [CheckboxComponent, SvgIconComponent],
  templateUrl: './checkbox-box-selection-info.component.html',
  styleUrls: ['./checkbox-box-selection-info.component.scss'],
})
export class CheckboxBoxSelectionInfoComponent {

  public readonly Icons = Icons;
}
`,
  },
  {
    language: 'scss',
    filename: 'global.scss',
    code: `
      :root {--cck-checkbox-border-color: var(--color-disabled-surface);
        --cck-checkbox-border-width: 1px;
        --cck-checkbox-border-style: solid;
        --cck-checkbox-border-radius: 12px;
        --cck-checkbox-padding: 16px;
        --cck-checkbox-gap: var(--toggle-spacing-gap);
        --cck-checkbox-box-gap: var(--toggle-size-backdrop-sm);
        --cck-checkbox-icon-color: #D0D0D4;
      }`,
    visibleConditions: [(theme) => theme.id === ThemeId.CocoKits],
  },
  {
    language: 'scss',
    filename: 'global.scss',
    code: `
      :root {--cck-checkbox-border-color: var(--base-border);
        --cck-checkbox-border-width: var(--spacing-1);
        --cck-checkbox-border-style: solid;
        --cck-checkbox-border-radius: var(--radi-6);
        --cck-checkbox-padding: var(--spacing-8);
        --cck-checkbox-gap: var(--spacing-7);
        --cck-checkbox-box-gap: var(--spacing-5);
        --cck-checkbox-icon-color: var(--colors-gray-300);
      }`,
    visibleConditions: [(theme) => theme.id === ThemeId.FramesX],
  },
];
