// (Do not edit directly)
// (Auto generated by the Cocokits 'generate-example-story-source' on Tue Mar 11 2025

import { AddonParametersSource, ThemeId } from '@cocokits/storybook-addon-theme';

export const SOURCE: AddonParametersSource[] = [
  {
    language: 'angular-ts',
    filename: 'prefix-icon-select.component.ts',
    code: `
import { Component, input, signal } from '@angular/core';

import {
  FormFieldComponent,
  LabelComponent,
  OptionComponent,
  PrefixComponent,
  SelectComponent,
  SvgIconComponent,
} from '@cocokits/angular-components';
import { Icons } from '@cocokits/common-icons';


@Component({
  standalone: true,
  selector: 'cck-prefix-icon-select',
  imports: [FormFieldComponent, LabelComponent, SelectComponent, OptionComponent, SvgIconComponent, PrefixComponent],
  template: \`
    <cck-form-field>
      <cck-label>Favorite food</cck-label>
      <cck-prefix>
        <cck-svg-icon [icon]="iconMap[value()]" />
      </cck-prefix>
      <cck-select class="select" [value]="value()" (selectionChange)="value.set($event[0])" appendTo="body">
        <cck-option value="Cake">
          <div class="option-wrapper">
            <cck-svg-icon [icon]="iconMap.Cake"></cck-svg-icon>
            Cake
          </div>
        </cck-option>
        <cck-option value="Pizza">
          <div class="option-wrapper">
            <cck-svg-icon [icon]="iconMap.Pizza"></cck-svg-icon>
            Pizza
          </div>
        </cck-option>
        <cck-option value="Burger">
          <div class="option-wrapper">
            <cck-svg-icon [icon]="iconMap.Burger"></cck-svg-icon>
            Burger
          </div>
        </cck-option>
        <cck-option value="Steak">
          <div class="option-wrapper">
            <cck-svg-icon [icon]="iconMap.Steak"></cck-svg-icon>
            Steak
          </div>
        </cck-option>
      </cck-select>
    </cck-form-field>
  \`,
  styles: \`
    .select {
      min-width: 150px;
    }

    .option-wrapper {
      display: flex;
      align-items: center;
      gap: 8px;

      .cck-svg-icon {
        fill: currentColor;
      }
    }
  \`,
})
export class PrefixIconSelectComponent {

  protected Icons = Icons;

  protected iconMap: Record<'Cake' | 'Pizza' | 'Burger' | 'Steak', string> = {
    Cake: Icons.cake,
    Pizza: Icons.pizzaSlice,
    Burger: Icons.burger,
    Steak: Icons.steak,
  };

  protected value = signal<'Cake' | 'Pizza' | 'Burger' | 'Steak'>('Cake');
}
`,
  },
];
