/* eslint-disable */
// (Do not edit directly)
// (Auto generated by the Cocokits 'generate-example-story-source')

import { AddonParametersSource, ThemeId } from '@cocokits/storybook-addon-theme';

export const SOURCE: AddonParametersSource[] = [
  {
    language: 'tsx',
    filename: 'CheckboxBoxSelection.styled.tsx',
    code: `
import styled from 'styled-components';

const Container = styled.div\`
  display: flex;
  flex-direction: column;
  gap: var(--cck-checkbox-gap);
\`;

const Box = styled.div\`
  padding: var(--cck-checkbox-padding);
  border: var(--cck-checkbox-border-width) var(--cck-checkbox-border-style) var(--cck-checkbox-border-color);
  border-radius: var(--cck-checkbox-border-radius);
\`;

export const Styled = {
  Container,
  Box,
};
`,
  },
  {
    language: 'tsx',
    filename: 'CheckboxBoxSelection.tsx',
    code: `

import { Checkbox } from '@cocokits/react-components';

import { Styled } from './CheckboxBoxSelection.styled';

export function CheckboxBoxSelection() {
  return (
    <Styled.Container>
      <Styled.Box>
        <Checkbox value={1}>Vegetarian</Checkbox>
      </Styled.Box>
      <Styled.Box>
        <Checkbox value={2}>Gluten-Free</Checkbox>
      </Styled.Box>
    </Styled.Container>
  );
}
`,
  },
  {
    language: 'scss',
    filename: 'global.scss',
    code: `
      :root {--cck-checkbox-border-color: var(--color-disabled-surface);
        --cck-checkbox-border-width: 1px;
        --cck-checkbox-border-style: solid;
        --cck-checkbox-border-radius: 12px;
        --cck-checkbox-padding: 16px;
        --cck-checkbox-gap: var(--toggle-spacing-gap);
      }`,
    visibleConditions: [(theme) => theme.id === ThemeId.CocoKits],
  },
  {
    language: 'scss',
    filename: 'global.scss',
    code: `
      :root {--cck-checkbox-border-color: var(--base-border);
        --cck-checkbox-border-width: var(--spacing-1);
        --cck-checkbox-border-style: solid;
        --cck-checkbox-border-radius: var(--radi-6);
        --cck-checkbox-padding: var(--spacing-8);
        --cck-checkbox-gap: var(--spacing-7);
      }`,
    visibleConditions: [(theme) => theme.id === ThemeId.FramesX],
  },
];
