/**
 * Do not edit directly
 * Generated by coco-kits scssify-token executor on Sat Jun 15 2024 17:17:21 GMT+0200 (Central European Summer Time)
 */

export const theme = {
  color: {
    bg: {
      body: {
        alpha: {
          '0': 'var(--color-bg-body-alpha-0)',
          '1': 'var(--color-bg-body-alpha-1)',
          '2': 'var(--color-bg-body-alpha-2)',
          '3': 'var(--color-bg-body-alpha-3)',
          '4': 'var(--color-bg-body-alpha-4)',
          '5': 'var(--color-bg-body-alpha-5)',
          '6': 'var(--color-bg-body-alpha-6)',
          '7': 'var(--color-bg-body-alpha-7)',
          '8': 'var(--color-bg-body-alpha-8)',
          '9': 'var(--color-bg-body-alpha-9)',
          '10': 'var(--color-bg-body-alpha-10)',
        },
      },
      bodyInverse: {
        alpha: {
          '0': 'var(--color-bg-body-inverse-alpha-0)',
          '1': 'var(--color-bg-body-inverse-alpha-1)',
          '2': 'var(--color-bg-body-inverse-alpha-2)',
          '3': 'var(--color-bg-body-inverse-alpha-3)',
          '4': 'var(--color-bg-body-inverse-alpha-4)',
          '5': 'var(--color-bg-body-inverse-alpha-5)',
          '6': 'var(--color-bg-body-inverse-alpha-6)',
          '7': 'var(--color-bg-body-inverse-alpha-7)',
          '8': 'var(--color-bg-body-inverse-alpha-8)',
          '9': 'var(--color-bg-body-inverse-alpha-9)',
          '10': 'var(--color-bg-body-inverse-alpha-10)',
        },
      },
      button: {
        primary: 'var(--color-bg-button-primary)',
        primaryHover: 'var(--color-bg-button-primary-hover)',
      },
      table: {
        even: 'var(--color-bg-table-even)',
      },
      overlay: {
        backdrop: 'var(--color-bg-overlay-backdrop)',
        shadow1: 'var(--color-bg-overlay-shadow-1)',
        shadow2: 'var(--color-bg-overlay-shadow-2)',
        default: 'var(--color-bg-overlay-default)',
      },
    },
    brand: {
      alpha0: 'var(--color-brand-alpha-0)',
      alpha1: 'var(--color-brand-alpha-1)',
      alpha2: 'var(--color-brand-alpha-2)',
      alpha3: 'var(--color-brand-alpha-3)',
      alpha4: 'var(--color-brand-alpha-4)',
      alpha5: 'var(--color-brand-alpha-5)',
      alpha6: 'var(--color-brand-alpha-6)',
      alpha7: 'var(--color-brand-alpha-7)',
      alpha8: 'var(--color-brand-alpha-8)',
      alpha9: 'var(--color-brand-alpha-9)',
      alpha10: 'var(--color-brand-alpha-10)',
      default: 'var(--color-brand-default)',
    },
    font: {
      contrast1: 'var(--color-font-contrast-1)',
      contrast2: 'var(--color-font-contrast-2)',
      contrast3: 'var(--color-font-contrast-3)',
      contrast4: 'var(--color-font-contrast-4)',
    },
    border: {
      card: {
        default: 'var(--color-border-card-default)',
      },
      alpha: {
        '0': 'var(--color-border-alpha-0)',
        '1': 'var(--color-border-alpha-1)',
        '2': 'var(--color-border-alpha-2)',
        '3': 'var(--color-border-alpha-3)',
        '4': 'var(--color-border-alpha-4)',
        '5': 'var(--color-border-alpha-5)',
        '6': 'var(--color-border-alpha-6)',
        '7': 'var(--color-border-alpha-7)',
        '8': 'var(--color-border-alpha-8)',
        '9': 'var(--color-border-alpha-9)',
        '10': 'var(--color-border-alpha-10)',
        default: 'var(--color-border-alpha-default)',
      },
      button: {
        primary: 'var(--color-border-button-primary)',
        primaryHover: 'var(--color-border-button-primary-hover)',
      },
    },
  },
};
