import { TokenCollectionName, TokenModeName } from '@cocokits/core';

import { CORE_FOLDER_NAME } from './builder.config';

// tokenDictionary
export function getTokenDictionaryFileHeader() {
  return `/* eslint-disable */
import { TokenDictionary } from '@cocokits/core';  

/**
 * Do not edit directly
 * Generated by cocokits token-generator on ${new Date()}
 */
 
export const tokenDictionary: TokenDictionary = `;
}

// Mixins
export function getCoreFileName(collectionName: TokenCollectionName, modeName: TokenModeName) {
  return `_${collectionName}.${modeName}.mixin.scss`;
}

export function getMixinBaseName(collectionName: TokenCollectionName, modeName: TokenModeName) {
  return `${collectionName}_${modeName}`;
}

export function getImportFileName(fileName: string): string {
  return fileName.replace(/^_/, '').replace(/\.scss$/, '');
}

export function getDefaultFileHeader() {
  return `/* eslint-disable */
/**
 * Do not edit directly
 * Generated by cocokits token-generator on ${new Date()}
 */
 
 `;
}

// CSS
export function getCssFileName(collectionName: TokenCollectionName, modeName: TokenModeName) {
  return `${collectionName}.${modeName}.scss`;
}

export function getCssFileHeader(collectionName: TokenCollectionName, modeName: TokenModeName) {
  return `${getDefaultFileHeader()}
@use '../${CORE_FOLDER_NAME}/${getCoreFileName(collectionName, modeName).replace('.scss', '')}' as *;

`;
}

// SCSS
export function getScssFileName(collectionName: TokenCollectionName) {
  return `_${collectionName}.scss`;
}
