import { MIXIN_FOLDER_NAME } from './builder.config';
import { TokenCollectionName, TokenModeName } from '@cocokits/core';

// tokenDictionary
export function getTokenDictionaryFileHeader() {
  return `/* eslint-disable max-lines */
  
import { TokenDictionary } from '@cocokits/workspace-plugin';  

/**
 * Do not edit directly
 * Generated by cocokits token-generator on ${new Date()}
 */
 
export const tokenDictionary: TokenDictionary = `;
}

// Mixins
export function getMixinFileName(collectionName: TokenCollectionName, modeName: TokenModeName) {
  return `_${collectionName}.${modeName}.mixin.scss`;
}

export function getMixinName(collectionName: TokenCollectionName, modeName: TokenModeName) {
  return `${collectionName}__${modeName}`;
}

export function getMixinFileHeader(collectionName: TokenCollectionName, modeName: TokenModeName) {
  return `/* eslint-disable max-lines */

/**
 * Do not edit directly
 * Generated by cocokits token-generator on ${new Date()}
 */

@mixin ${getMixinName(collectionName, modeName)} {
 `;
}

// CSS
export function getCssFileName(collectionName: TokenCollectionName, modeName: TokenModeName) {
  return `${collectionName}.${modeName}.scss`;
}

export function getCssFileHeader(collectionName: TokenCollectionName, modeName: TokenModeName) {
  return `/* eslint-disable max-lines */

/**
 * Do not edit directly
 * Generated by cocokits token-generator on ${new Date()}
 */

@use '../${MIXIN_FOLDER_NAME}/${getMixinFileName(collectionName, modeName).replace('.scss', '')}' as *;

`;
}

export function getIndexFileHeader() {
  return `/* eslint-disable max-lines */

/**
 * Do not edit directly
 * Generated by cocokits token-generator on ${new Date()}
 */
`;
}

// SCSS
export function getScssFileName(collectionName: TokenCollectionName) {
  return `_${collectionName}.scss`;
}

export function getScssFileHeader() {
  return `/* eslint-disable max-lines */

/**
 * Do not edit directly
 * Generated by cocokits token-generator on ${new Date()}
 */

`;
}
