// (Do not edit directly)
// (Auto generated by the Cocokits 'generate-example-story-source' on Sat Mar 22 2025

import { AddonParametersSource, ThemeId } from '@cocokits/storybook-addon-theme';

export const SOURCE: AddonParametersSource[] = [
  {
    language: 'tsx',
    filename: 'LeadingIcon.tsx',
    code: `
import { Icons } from '@cocokits/common-icons';

import { FormField, Input, Label, Leading, SvgIcon } from '@cocokits/react-components';

export function LeadingIcon() {
  return (
    <FormField>
      <Label>Enter username</Label>
      <Leading>
        <SvgIcon icon={Icons.user}/>
      </Leading>
      <Input/>
    </FormField>
  );
}
`,
  },
];
