// (Do not edit directly)
// (Auto generated by the Cocokits 'generate-example-story-source' on Sat Mar 01 2025

import { AddonParametersSource, ThemeId } from '@cocokits/storybook-addon-theme';

export const SOURCE: AddonParametersSource[] = [
  {
    language: 'angular-ts',
    filename: 'leading-icon.component.ts',
    code: `
import { Component, input } from '@angular/core';

import {
  FormFieldComponent,
  InputComponent,
  LabelComponent,
  LeadingComponent,
  SvgIconComponent,
} from '@cocokits/angular-components';
import { Icons } from '@cocokits/common-icons';


@Component({
  standalone: true,
  selector: 'cck-leading-icon',
  imports: [FormFieldComponent, InputComponent, LeadingComponent, LabelComponent, SvgIconComponent],
  template: \`
    <cck-form-field>
      <cck-label>Enter username</cck-label>
      <cck-leading>
        <cck-svg-icon [icon]="Icons.user"></cck-svg-icon>
      </cck-leading>
      <input cck-input />
    </cck-form-field>
  \`,
  styles: \`\`,
})
export class LeadingIconComponent {

  protected readonly Icons = Icons;
}
`,
  },
];
