/* eslint-disable */
// (Do not edit directly)
// (Auto generated by the Cocokits 'generate-example-story-source')

import { AddonParametersSource, ThemeId } from '@cocokits/storybook-addon-theme';

export const SOURCE: AddonParametersSource[] = [
  {
    language: 'tsx',
    filename: 'CheckboxBoxSelectionInfo.styled.tsx',
    code: `
import styled from 'styled-components';

const Container = styled.div\`
  display: flex;
  flex-direction: column;
  gap: var(--cck-checkbox-gap);
\`;

const Box = styled.div\`
  padding: var(--cck-checkbox-padding);
  border: var(--cck-checkbox-border-width) var(--cck-checkbox-border-style) var(--cck-checkbox-border-color);
  border-radius: var(--cck-checkbox-border-radius);

  direction: rtl;
  display: flex;
  align-items: center;
  gap: var(--cck-checkbox-box-gap);

  svg {
    fill: var(--cck-checkbox-icon-color);
  }
\`;

export const Styled = {
  Container,
  Box,
};
`,
  },
  {
    language: 'tsx',
    filename: 'CheckboxBoxSelectionInfo.tsx',
    code: `
import { Icons } from '@cocokits/common-icons';

import { Checkbox, SvgIcon } from '@cocokits/react-components';

import { Styled } from './CheckboxBoxSelectionInfo.styled';

export function CheckboxBoxSelectionInfo() {
  return (
    <Styled.Container>
      <Styled.Box>
        <Checkbox value={1}>Leave at Door</Checkbox>
        <SvgIcon icon={Icons.info} size='<%= IconSize %>' />
      </Styled.Box>
      <Styled.Box>
        <Checkbox value={2}>Call on Arrival</Checkbox>
        <SvgIcon icon={Icons.info} size='<%= IconSize %>' />
      </Styled.Box>
    </Styled.Container>
  );
}
`,
  },
  {
    language: 'scss',
    filename: 'global.scss',
    code: `
      :root {--cck-checkbox-border-color: var(--color-disabled-surface);
        --cck-checkbox-border-width: 1px;
        --cck-checkbox-border-style: solid;
        --cck-checkbox-border-radius: 12px;
        --cck-checkbox-padding: 16px;
        --cck-checkbox-gap: var(--toggle-spacing-gap);
        --cck-checkbox-box-gap: var(--toggle-size-backdrop-sm);
        --cck-checkbox-icon-color: #D0D0D4;
      }`,
    visibleConditions: [(theme) => theme.id === ThemeId.CocoKits],
  },
  {
    language: 'scss',
    filename: 'global.scss',
    code: `
      :root {--cck-checkbox-border-color: var(--base-border);
        --cck-checkbox-border-width: var(--spacing-1);
        --cck-checkbox-border-style: solid;
        --cck-checkbox-border-radius: var(--radi-6);
        --cck-checkbox-padding: var(--spacing-8);
        --cck-checkbox-gap: var(--spacing-7);
        --cck-checkbox-box-gap: var(--spacing-5);
        --cck-checkbox-icon-color: var(--colors-gray-300);
      }`,
    visibleConditions: [(theme) => theme.id === ThemeId.FramesX],
  },
];
