/* eslint-disable */
// (Do not edit directly)
// (Auto generated by the Cocokits 'generate-example-story-source')

import { AddonParametersSource, ThemeId } from '@cocokits/storybook-addon-theme';

export const SOURCE: AddonParametersSource[] = [
  {
    language: 'tsx',
    filename: 'CheckboxLabelLink.tsx',
    code: `

import { Checkbox } from '@cocokits/react-components';

export function CheckboxLabelLink() {
  return (
    <Checkbox value={1}>
      I accept the
      <a href="https://cocokits.com" target="_blank" rel="noopener noreferrer">
        Privacy Policy
      </a>
    </Checkbox>
  );
}
`,
  },
];
