/* eslint-disable */
// (Do not edit directly)
// (Auto generated by the Cocokits 'generate-example-story-source')

import { AddonParametersSource, ThemeId } from '@cocokits/storybook-addon-theme';

export const SOURCE: AddonParametersSource[] = [
  {
    language: 'tsx',
    filename: 'CheckboxLabelLink.tsx',
    code: `

import { Checkbox } from '@cocokits/react-checkbox';

export function CheckboxLabelLink() {
  return (
    <Checkbox>
      I accept the <a href="/">Privacy Policy</a>
    </Checkbox>
  );
}
`,
  },
];
