// (Do not edit directly)
// (Auto generated by the Cocokits 'generate-example-story-source' on Wed Mar 26 2025

import { AddonParametersSource, ThemeId } from '@cocokits/storybook-addon-theme';

export const SOURCE: AddonParametersSource[] = [
  {
    language: 'tsx',
    filename: 'CheckboxGroupColumn.tsx',
    code: `

import { Checkbox } from '@cocokits/react-checkbox';

export function CheckboxGroupColumn() {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
      <i style={{ color: 'var(--checkbox-group-column-color)' }}>My hobbies</i>
      <Checkbox size='<%= size %>' value={1}>
        Comic books
      </Checkbox>
      <Checkbox size='<%= size %>' value={1}>
        Listen to music
      </Checkbox>
      <Checkbox size='<%= size %>' value={1}>
        Travel the world
      </Checkbox>
      <Checkbox size='<%= size %>' value={1}>
        Watch movies
      </Checkbox>
    </div>
  );
}
`,
  },
  {
    language: 'scss',
    filename: 'global.scss',
    code: `
      :root {--checkbox-group-column-color: var(--color-palette-gray-800);
      }`,
    visibleConditions: [(theme) => theme.id === ThemeId.CocoKits],
  },
  {
    language: 'scss',
    filename: 'global.scss',
    code: `
      :root {--checkbox-group-column-color: var(--colors-gray-300);
      }`,
    visibleConditions: [(theme) => theme.id === ThemeId.FramesX],
  },
];
