/* eslint-disable */
// (Do not edit directly)
// (Auto generated by the Cocokits 'generate-example-story-source')

import { AddonParametersSource, ThemeId } from '@cocokits/storybook-addon-theme';

export const SOURCE: AddonParametersSource[] = [
  {
    language: 'tsx',
    filename: 'CheckboxGroupColumn.styled.tsx',
    code: `
import styled from 'styled-components';

const Label = styled.span\`
  color: var(--checkbox-group-column-color);
  font-style: italic;
  font-family: var(--checkbox-group-column-font-family);
\`;

const CheckboxGroupColumn = styled.div\`
  display: flex;
  flex-direction: column;
  gap: 12px;
\`;

export const Styled = {
  Label,
  CheckboxGroupColumn,
};
`,
  },
  {
    language: 'tsx',
    filename: 'CheckboxGroupColumn.tsx',
    code: `

import { Checkbox } from '@cocokits/react-components';

import { Styled } from './CheckboxGroupColumn.styled';

export function CheckboxGroupColumn() {
  return (
    <Styled.CheckboxGroupColumn>
      <Styled.Label>My hobbies</Styled.Label>
      <Checkbox size='<%= size %>' value={1}>
        Comic books
      </Checkbox>
      <Checkbox size='<%= size %>' value={2}>
        Listen to music
      </Checkbox>
      <Checkbox size='<%= size %>' value={3}>
        Travel the world
      </Checkbox>
      <Checkbox size='<%= size %>' value={4}>
        Watch movies
      </Checkbox>
    </Styled.CheckboxGroupColumn>
  );
}
`,
  },
  {
    language: 'scss',
    filename: 'global.scss',
    code: `
      :root {--checkbox-group-column-color: var(--color-palette-gray-800);
        --checkbox-group-column-font-family: Inter;
      }`,
    visibleConditions: [(theme) => theme.id === ThemeId.CocoKits],
  },
  {
    language: 'scss',
    filename: 'global.scss',
    code: `
      :root {--checkbox-group-column-color: var(--colors-gray-300);
        --checkbox-group-column-font-family: var(--font-family);
      }`,
    visibleConditions: [(theme) => theme.id === ThemeId.FramesX],
  },
];
