// (Do not edit directly)
// (Auto generated by the Cocokits 'generate-example-story-source' on Sun Mar 09 2025

import { AddonParametersSource, ThemeId } from '@cocokits/storybook-addon-theme';

export const SOURCE: AddonParametersSource[] = [
  {
    language: 'angular-ts',
    filename: 'show-more-button.component.ts',
    code: `
import { Component, input } from '@angular/core';

import { ButtonComponent, SvgIconComponent } from '@cocokits/angular-components';
import { Icons } from '@cocokits/common-icons';


@Component({
  standalone: true,
  selector: 'cck-show-more-button',
  imports: [ButtonComponent, SvgIconComponent],
  template: \`
    <button cck-button [type]="'<%=buttonType%>'" [color]="'<%=buttonColor%>'">
      <span>Show More</span>
      <cck-svg-icon [icon]="Icons.arrowHeadDown"></cck-svg-icon>
    </button>
  \`,
  styles: \`\`,
})
export class ShowMoreButtonComponent {

  public readonly Icons = Icons;
}
`,
  },
];
