import { THEME_HTML_ATTRIBUTE_MODE_NAME, THEME_HTML_ATTRIBUTE_THEME_NAME } from '../config/events.config';
import { ColorMode, SelectedTheme } from '../model/theme.model';

const ADDON_THEME_CLASSES = [
  /**
   * Add custom CSS selectors using this prefix to select an element in order to override the style.
   * This will help us easily debug and find our custom styles in the browser.
   */
  'cck-theme-storybook-addon',
  /**
   * The CSS selectors are generated by CocoKits `token-generator`, so don't change it manually
   * To find all selectors, check the output of the `token-generator` target in the `project.json` file of the `storybook-addon-theme` library.
   */
  'cck-theme-storybook-addon__color-palette--default',
  'cck-theme-storybook-addon__size--default',
  'cck-theme-storybook-addon__local-style--default',
];

/**
 * The CSS selectors are generated by CocoKits `token-generator`, so don't change it manually
 * To find all selectors, check the output of the `token-generator` target in the `project.json` file of the `storybook-addon-theme` library.
 */
export const ADDON_COLOR_MODE_CSS_SELECTORS: Record<ColorMode, string> = {
  [ColorMode.Dark]: 'cck-theme-storybook-addon__color--dark',
  [ColorMode.Light]: 'cck-theme-storybook-addon__color--light',
};

export class DocumentStyle {
  public setColoMode(colorMode: ColorMode) {
    document.documentElement.classList.remove(...Object.values(ADDON_COLOR_MODE_CSS_SELECTORS));
    document.documentElement.classList.add(ADDON_COLOR_MODE_CSS_SELECTORS[colorMode]);
  }

  public setTheme(selectedThem: SelectedTheme) {
    const attr = Object.entries(selectedThem.selectedModes)
      .map(([collectionName, mode]) => `${selectedThem.id}__${collectionName}--${mode}`)
      .join(' ');

    document.documentElement.setAttribute(THEME_HTML_ATTRIBUTE_MODE_NAME, attr);
    document.documentElement.setAttribute(THEME_HTML_ATTRIBUTE_THEME_NAME, selectedThem.id);
  }

  public setAddonTheme() {
    document.documentElement.classList.add(...ADDON_THEME_CLASSES);
  }

  public setAddonHideToolbar() {
    document.documentElement.classList.add('cck-theme-storybook-addon--remove-toolbar');
  }
}
