/* eslint-disable max-lines */

/**
 * Do not edit directly
 * Generated by coco-kits scssify-token executor on Fri Jun 21 2024 17:41:04 GMT+0200 (Central European Summer Time)
 */

export const colorTheme = {
  fill: {
    '50': 'var(--fill-50)',
    '100': 'var(--fill-100)',
    '200': 'var(--fill-200)',
    '300': 'var(--fill-300)',
    '400': 'var(--fill-400)',
    '600': 'var(--fill-600)',
    '00': 'var(--fill-00)',
  },
  state: {
    base: {
      background: 'var(--state-base-background)',
      border: 'var(--state-base-border)',
      disabled: 'var(--state-base-disabled)',
    },
    primary: {
      active: 'var(--state-primary-active)',
      hover: 'var(--state-primary-hover)',
      selected: 'var(--state-primary-selected)',
    },
    destructive: {
      active: 'var(--state-destructive-active)',
      hover: 'var(--state-destructive-hover)',
      selected: 'var(--state-destructive-selected)',
    },
    highlight: {
      active: 'var(--state-highlight-active)',
      hover: 'var(--state-highlight-hover)',
      selected: 'var(--state-highlight-selected)',
    },
    success: {
      active: 'var(--state-success-active)',
      hover: 'var(--state-success-hover)',
      selected: 'var(--state-success-selected)',
    },
  },
};
