/* eslint-disable max-lines */

/**
 * Do not edit directly
 * Generated by coco-kits scssify-token executor on Fri Jun 21 2024 17:41:04 GMT+0200 (Central European Summer Time)
 */

export const radius = {
  radi0: 'var(--radi-0)',
  radi1: 'var(--radi-1)',
  radi2: 'var(--radi-2)',
  radi3: 'var(--radi-3)',
  radi4: 'var(--radi-4)',
  radi5: 'var(--radi-5)',
  radi6: 'var(--radi-6)',
  radi7: 'var(--radi-7)',
  radi8: 'var(--radi-8)',
  radi9: 'var(--radi-9)',
  radi10: 'var(--radi-10)',
};
