/* eslint-disable max-lines */

/**
 * Do not edit directly
 * Generated by cocokits scssify-token executor on Fri Jun 21 2024 17:41:04 GMT+0200 (Central European Summer Time)
 */

export const sizing = {
  spacing: {
    space0: 'var(--spacing-space-0)',
    space1: 'var(--spacing-space-1)',
    space2: 'var(--spacing-space-2)',
    space3: 'var(--spacing-space-3)',
    space4: 'var(--spacing-space-4)',
    space5: 'var(--spacing-space-5)',
    space6: 'var(--spacing-space-6)',
    space7: 'var(--spacing-space-7)',
    space8: 'var(--spacing-space-8)',
    space9: 'var(--spacing-space-9)',
    space10: 'var(--spacing-space-10)',
    space11: 'var(--spacing-space-11)',
    space12: 'var(--spacing-space-12)',
    space13: 'var(--spacing-space-13)',
    space14: 'var(--spacing-space-14)',
    space15: 'var(--spacing-space-15)',
    space16: 'var(--spacing-space-16)',
    space17: 'var(--spacing-space-17)',
    space18: 'var(--spacing-space-18)',
    space19: 'var(--spacing-space-19)',
    space20: 'var(--spacing-space-20)',
    space21: 'var(--spacing-space-21)',
    space22: 'var(--spacing-space-22)',
    space23: 'var(--spacing-space-23)',
    space24: 'var(--spacing-space-24)',
    space25: 'var(--spacing-space-25)',
    space26: 'var(--spacing-space-26)',
    space27: 'var(--spacing-space-27)',
    space28: 'var(--spacing-space-28)',
    space29: 'var(--spacing-space-29)',
    space30: 'var(--spacing-space-30)',
    space31: 'var(--spacing-space-31)',
    space32: 'var(--spacing-space-32)',
    space33: 'var(--spacing-space-33)',
  },
  icon: {
    iconXs: 'var(--icon-icon-xs)',
    iconSm: 'var(--icon-icon-sm)',
    iconMd: 'var(--icon-icon-md)',
    iconLg: 'var(--icon-icon-lg)',
    iconXl: 'var(--icon-icon-xl)',
    icon2Xl: 'var(--icon-icon-2xl)',
    icon3Xl: 'var(--icon-icon-3xl)',
    icon4Xl: 'var(--icon-icon-4xl)',
  },
};
