/* eslint-disable @typescript-eslint/no-unused-vars */
// (Do not edit directly)
// (Auto generated by the Cocokits 'generate-example-story-source' on Tue Mar 25 2025

import { AddonParametersSource, ThemeId } from '@cocokits/storybook-addon-theme';

export const SOURCE: AddonParametersSource[] = [
  {
    language: 'angular-ts',
    filename: 'checkbox-label-link.component.ts',
    code: `
import { Component, input } from '@angular/core';

import { CheckboxComponent } from '@cocokits/angular-checkbox';


@Component({
  standalone: true,
  selector: 'cck-checkbox-label-link',
  imports: [CheckboxComponent],
  template: \` <cck-checkbox>I accept the <a href="/">Privacy Policy</a></cck-checkbox> \`,
  styles: \`\`,
})
export class CheckboxLabelLinkComponent {

}
`,
  },
];
