/* eslint-disable */
// (Do not edit directly)
// (Auto generated by the Cocokits 'generate-example-story-source')

import { AddonParametersSource, ThemeId } from '@cocokits/storybook-addon-theme';

export const SOURCE: AddonParametersSource[] = [
  {
    language: 'angular-ts',
    filename: 'checkbox-label-through.component.ts',
    code: `
import { Component, input } from '@angular/core';

import { CheckboxComponent } from '@cocokits/angular-checkbox';


@Component({
  standalone: true,
  selector: 'cck-checkbox-label-through',
  imports: [CheckboxComponent],
  template: \`
    <cck-checkbox [size]="'<%=size%>'" [value]="1"
      ><span class="striked-label"> Checkbox Label </span></cck-checkbox
    >
  \`,
  styles: \`
    .striked-label {
      text-decoration: line-through;
    }
  \`,
})
export class CheckboxLabelThroughComponent {

}
`,
  },
];
