// (Do not edit directly)
// (Auto generated by the Cocokits 'generate-example-story-source' on Wed Mar 05 2025

import { AddonParametersSource, ThemeId } from '@cocokits/storybook-addon-theme';

export const SOURCE: AddonParametersSource[] = [
  {
    language: 'angular-ts',
    filename: 'suffix-card-pattern.component.ts',
    code: `
import { Component, input } from '@angular/core';

import { NgxMaskDirective, provideNgxMask } from 'ngx-mask';

import {
  FormFieldComponent,
  InputComponent,
  LabelComponent,
  SuffixComponent,
  SvgIconComponent,
} from '@cocokits/angular-components';
import { Icons } from '@cocokits/common-icons';


@Component({
  standalone: true,
  selector: 'cck-suffix-card-pattern',
  imports: [FormFieldComponent, LabelComponent, InputComponent, SuffixComponent, SvgIconComponent, NgxMaskDirective],
  providers: [provideNgxMask()],
  template: \`
    <cck-form-field>
      <cck-label>Card information</cck-label>
      <input cckInput mask="9999 9999 9999 9999" />
      <cck-suffix>
        <cck-svg-icon [icon]="Icons.card"></cck-svg-icon>
      </cck-suffix>
    </cck-form-field>
  \`,
  styles: \`\`,
})
export class SuffixCardPatternComponent {

  protected Icons = Icons;
}
`,
  },
];
