/* eslint-disable max-lines */

/**
 * Do not edit directly
 * Generated by cocokits scssify-token executor on Sat Jul 20 2024 22:23:15 GMT+0200 (Central European Summer Time)
 */

export const collections = {
  'local-style': ['default'],
  global: ['default'],
  components: ['default'],
  'brand-color-1': ['light', 'dark'],
};
