/* eslint-disable max-lines */

/**
 * Do not edit directly
 * Generated by coco-kits scssify-token executor on Thu Jun 20 2024 21:48:21 GMT+0200 (Central European Summer Time)
 */

export const collections = {
  'local-style': ['default'],
  global: ['default'],
  'components-size': ['default'],
  'brand-color-1': ['light', 'dark'],
};
