/* eslint-disable max-lines */

/**
 * Do not edit directly
 * Generated by cocokits scssify-token executor on Wed Jul 17 2024 19:57:37 GMT+0200 (Central European Summer Time)
 */

export const collections = {
  'local-style': ['default'],
  global: ['default'],
  components: ['default'],
  'brand-color-1': ['light', 'dark'],
};
