/* eslint-disable */
// (Do not edit directly)
// (Auto generated by the Cocokits 'generate-example-story-source')

import { AddonParametersSource, ThemeId } from '@cocokits/storybook-addon-theme';

export const SOURCE: AddonParametersSource[] = [
  {
    language: 'angular-ts',
    filename: 'input-side-label.component.ts',
    code: `
import { Component, input } from '@angular/core';

import { FormFieldComponent, InputComponent, LabelComponent } from '@cocokits/angular-form-field';


@Component({
  selector: 'cck-input-side-label',
  imports: [FormFieldComponent, LabelComponent, InputComponent],
  template: \`
    <cck-label for="city">City</cck-label>
    <cck-form-field>
      <input cck-input id="city" />
    </cck-form-field>

    <cck-label for="country">Country</cck-label>
    <cck-form-field>
      <input cck-input id="country" />
    </cck-form-field>
  \`,
  styles: \`
    :host {
      display: grid;
      grid-template-columns: auto 1fr;
      grid-template-rows: 1fr 1fr;
      align-items: center;
      justify-items: end;
      gap: 8px 12px;
    }
  \`,
})
export class InputSideLabelComponent {

}
`,
  },
];
