// (Do not edit directly)
// (Auto generated by the Cocokits 'generate-example-story-source' on Thu Feb 27 2025

import { AddonParametersSource, ThemeId } from '@cocokits/storybook-addon-theme';

export const SOURCE: AddonParametersSource[] = [
  {
    language: 'tsx',
    filename: 'TrailingCustomColor.styled.tsx',
    code: `
import styled from "styled-components";

import { Trailing } from "@cocokits/react-components";

const _Trailing = styled(Trailing)\`
  background-color: var(--trailing-color);
\`;

export const Styled = {
  Trailing: _Trailing,
};`,
  },
  {
    language: 'tsx',
    filename: 'TrailingCustomColor.tsx',
    code: `
import { Icons } from '@cocokits/common-icons';

import { FormField, Input, Label, SvgIcon } from '@cocokits/react-components';

import { Styled } from './TrailingCustomColor.styled';

export function TrailingCustomColor() {
  return (
    <FormField>
      <Label>Subscribe</Label>
      <Input defaultValue="hello@cocokits.com"/>
      <Styled.Trailing clickable>
        <SvgIcon icon={Icons.arrowRight}/>
      </Styled.Trailing>
    </FormField>
  );
}
`,
  },
  {
    language: 'scss',
    filename: 'global.scss',
    code: `
      :root {--trailing-color: var(--color-brand-default);
      }`,
    visibleConditions: [(theme) => theme.id === ThemeId.CocoKits],
  },
  {
    language: 'scss',
    filename: 'global.scss',
    code: `
      :root {--trailing-color: var(--state-brand-active);
      }`,
    visibleConditions: [(theme) => theme.id === ThemeId.FramesX],
  },
];
