import fs from 'fs';
import path from 'path';

import { SOURCE_FILENAME } from '../executor.config';

export function generateSourceFiles(folder: string, source: string): string {
  const filePath = path.join(folder, SOURCE_FILENAME);
  fs.writeFileSync(path.join(folder, SOURCE_FILENAME), generateContent(source));
  return filePath;
}

function generateContent(source: string) {
  return `// (Do not edit directly)
// (Auto generated by the Cocokits 'generate-example-story-source' on ${new Date().toDateString()}
  
import { AddonParametersSource, ThemeId } from "@cocokits/storybook-addon-theme";
    
export const SOURCE: AddonParametersSource[] = [
  ${source.trim()}
];
`.trim();
}
