// (Do not edit directly)
// (Auto generated by the Cocokits 'generate-example-story-source' on Wed Mar 12 2025

import { AddonParametersSource, ThemeId } from '@cocokits/storybook-addon-theme';

export const SOURCE: AddonParametersSource[] = [
  {
    language: 'angular-ts',
    filename: 'flags.ts',
    code: `
export const ATFlag = \`
  <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
    <g clip-path="url(#clip0_1689_44360)">
    <path d="M23.2536 16.1741C23.736 14.8742 24 13.4681 24 12.0002C24 10.5324 23.736 9.12636 23.2536 7.82632L12 6.78284L0.746391 7.82632C0.264047 9.12636 0 10.5324 0 12.0002C0 13.4681 0.264047 14.8742 0.746391 16.1741L12 17.2176L23.2536 16.1741Z" fill="#F0F0F0"/>
    <path d="M12.0002 24.0001C17.1598 24.0001 21.5583 20.7436 23.2538 16.174H0.746582C2.44214 20.7436 6.84061 24.0001 12.0002 24.0001Z" fill="#D80027"/>
    <path d="M12.0002 0C6.84061 0 2.44214 3.2565 0.746582 7.82611H23.2538C21.5583 3.2565 17.1598 0 12.0002 0Z" fill="#D80027"/>
    </g>
    <defs>
    <clipPath id="clip0_1689_44360">
    <rect width="24" height="24" fill="white"/>
    </clipPath>
    </defs>
  </svg>
\`;

export const THFlag = \`
  <svg viewBox="0 0 24 25" fill="none" xmlns="http://www.w3.org/2000/svg">
    <g clip-path="url(#clip0_278_663)">
    <path d="M12 24.0715C18.6274 24.0715 24 18.6989 24 12.0715C24 5.44412 18.6274 0.0715332 12 0.0715332C5.37258 0.0715332 0 5.44412 0 12.0715C0 18.6989 5.37258 24.0715 12 24.0715Z" fill="#F0F0F0"/>
    <path d="M23.2536 7.89771H0.746391C0.264 9.19769 0 10.6038 0 12.0716C0 13.5394 0.264 14.9455 0.746391 16.2455H23.2537C23.736 14.9455 24 13.5394 24 12.0716C24 10.6038 23.736 9.19769 23.2536 7.89771Z" fill="#0052B4"/>
    <path d="M12 0.0715332C8.36294 0.0715332 5.10405 1.68985 2.90341 4.24542H21.0966C18.896 1.68985 15.6371 0.0715332 12 0.0715332Z" fill="#D80027"/>
    <path d="M21.0966 19.8977H2.90341C5.10405 22.4533 8.36294 24.0716 12 24.0716C15.6371 24.0716 18.896 22.4533 21.0966 19.8977Z" fill="#D80027"/>
    </g>
    <defs>
    <clipPath id="clip0_278_663">
    <rect width="24" height="24" fill="white" transform="translate(0 0.0715332)"/>
    </clipPath>
    </defs>
  </svg>
\`;
`,
  },
  {
    language: 'angular-ts',
    filename: 'PhoneNumber.styled.ts',
    code: `
import styled from 'styled-components';

import { Prefix as CckPrefix } from '@cocokits/react-components';

const Prefix = styled(CckPrefix)\`
  color: var(--prefix-color);
  font: var(--prefix-font);
\`;

const OptionWrapper = styled.div\`
  display: flex;
  align-items: center;
  gap: 8px;
\`;

export const Styled = {
  Prefix,
  OptionWrapper,
};
`,
  },
  {
    language: 'tsx',
    filename: 'PhoneNumber.tsx',
    code: `
import InputMask from '@mona-health/react-input-mask';
import { useState } from 'react';


import { FormField, Hint,Input, Label, Option ,Select,Suffix, SvgIcon } from '@cocokits/react-components';

import { ATFlag,THFlag } from './flags';
import { Styled } from './PhoneNumber.styled';


const FlagsMap = {
  'TH': THFlag,
  'AT': ATFlag
};

export function PhoneNumber() {
  const [value, setValue] = useState<'TH' | 'AT'>('TH');
  
  return (
    <FormField>
      <Label>Phone number</Label>
      <Styled.Prefix>+{ value === 'TH' ? '66' : '43' }</Styled.Prefix>
      <InputMask mask={value === 'TH' ? '999-999-999' : '999 9999 999'} maskPlaceholder={null}>
        <Input/>
      </InputMask>
      <Suffix>
        <Select
          value={value}
          onChange={(e) => setValue(e[0] as 'TH' | 'AT')}
          selectPreview={(selected) => (
            <SvgIcon size='<%= previewFlagSize %>' icon={FlagsMap[selected[0]]}/>
          )}>
          <Option value="TH">
            <Styled.OptionWrapper>
              <SvgIcon size='<%= optionFlagSize %>' icon={THFlag}/>
              TH
            </Styled.OptionWrapper>
          </Option>
          <Option value="AT">
            <Styled.OptionWrapper>
              <SvgIcon size='<%= optionFlagSize %>' icon={ATFlag}/>
              AT
            </Styled.OptionWrapper>
          </Option>
        </Select>
      </Suffix>
      <Hint>Enter your local phone number</Hint>
    </FormField>
  );
}
`,
  },
  {
    language: 'scss',
    filename: 'global.scss',
    code: `
      :root {--prefix-color: var(--color-font-alpha-7);
        --prefix-font: var(--text-xs-regular);
      }`,
    visibleConditions: [(theme) => theme.id === ThemeId.CocoKits],
  },
  {
    language: 'scss',
    filename: 'global.scss',
    code: `
      :root {--prefix-color: var(--text-dark-tertiary);
        --prefix-font: var(--text-base-font-medium);
      }`,
    visibleConditions: [(theme) => theme.id === ThemeId.FramesX],
  },
];
