import { ColorMode } from '../model/theme.model';

export const EVENTS = {
  // Theme
  THEME_CHANGE: 'cocokits_theme-changed',

  // Color Mode
  COLOR_MODE_CHANGE: 'cocokits_color-mode-changed',

  // Theme Selection
  OPEN_THEME_SELECTION: 'cocokits_open-theme-selection',
  THEME_SELECTION_CLOSED: 'cocokits_theme-selection-closed',

  // Story Control
  OPEN_STORY_CONTROL: 'cocokits_open-story-control',
  STORY_CONTROL_CLOSED: 'cocokits_story-control-closed',
  STORY_CONTROL_CHANGED: 'cocokits_story-control-changed',
};

export const THEME_HTML_ATTRIBUTE_MODE_NAME = 'data-cck-theme';
export const THEME_HTML_ATTRIBUTE_THEME_NAME = 'data-cck-theme-name';

/**
 * The CSS selectors are generated by CocoKits `token-generator`, so don't change it manually
 * To find all selectors, check the output of the `token-generator` target in the `project.json` file of the `storybook-addon-theme` library.
 */
export const COLOR_MODE_CSS_SELECTORS: Record<ColorMode, string> = {
  [ColorMode.Dark]: 'cck-theme-storybook-addon__color--dark',
  [ColorMode.Light]: 'cck-theme-storybook-addon__color--light',
};
