name: "Main branch PR [Build, Test]"

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch latest from main branch
        run: git fetch --no-tags --depth=1 origin main:main

      - name: Install Dependencies
        uses: ./.github/actions/pnpm-install


      # In CI, the packages will be not build in the correct order. As a quick fix we build the react project first and then run build all
      # - name: Build Quick Fix
      #  run: pnpm nx affected:build --base=main --head=HEAD --exclude=@cocokits/angular-* --parallel=4

      - name: Check Dependencies
        run: pnpm exec nx run cocokits:depcheck

      - name: Build All
        run: pnpm nx affected:build --base=main --head=HEAD --exclude=website --parallel=4

      - name: Test
        run: pnpm nx affected:test --base=main --head=HEAD --exclude=cocokits,website --parallel=1