/* eslint-disable */
// (Do not edit directly)
// (Auto generated by the Cocokits 'generate-example-story-source')

import { AddonParametersSource, ThemeId } from '@cocokits/storybook-addon-theme';

export const SOURCE: AddonParametersSource[] = [
  {
    language: 'angular-ts',
    filename: 'mode-toggle.component.ts',
    code: `
import { Component, computed, input, signal } from '@angular/core';

import { IconButtonComponent, SvgIconComponent } from '@cocokits/angular-components';
import { Icons } from '@cocokits/common-icons';


@Component({
  standalone: true,
  selector: 'cck-mode-toggle',
  imports: [IconButtonComponent, SvgIconComponent],
  template: \` <button
    cck-icon-button
    [color]="'<%=color%>'"
    [type]="'<%=type%>'"
    [size]="'<%=size%>'"
    (click)="isDark.set(!isDark())">
    <cck-svg-icon [icon]="icon()" [size]="'<%=iconSize%>'" />
  </button>\`,
  styles: \`\`,
})
export class ModeToggleComponent {


  protected isDark = signal(false);
  protected icon = computed(() => (this.isDark() ? Icons.light : Icons.dark));
  protected readonly Icons = Icons;
}
`,
  },
];
