import autoprefixer from 'autoprefixer';
import cssnano from 'cssnano';
import * as fs from 'fs';
import * as path from 'path';
import postcss from 'postcss';
import discardComments from 'postcss-discard-comments';
import * as sass from 'sass';
import { OutputStyle } from 'sass/types/options';

import { whereSelectorPlugin } from './where-selector-plugin';
import { Logger } from '../../utils/logger';

interface CssBuilderOptions {
  outputStyle: OutputStyle;
  sourceMap: boolean;
  outputPath: string;
  wrapWithWhereSudo: boolean;
}

export async function cssBuilder(
  scssPath: string,
  options: CssBuilderOptions
): Promise<{ cssPath: string; sourceMapPath: string | null }> {
  const scssParsedPath = path.parse(scssPath);

  const sassCompileResult = sass.compile(scssPath, {
    style: options.outputStyle,
    sourceMap: options.sourceMap,
    sourceMapIncludeSources: options.sourceMap,
  });

  const postCssPlugins: postcss.AcceptedPlugin[] =
    options.outputStyle === 'expanded'
      ? [autoprefixer({ cascade: false }), discardComments({ removeAll: true })]
      : [autoprefixer({ cascade: false }), cssnano()];

  if (options.wrapWithWhereSudo) {
    postCssPlugins.push(whereSelectorPlugin());
  }

  const cssOutputPath =
    options.outputStyle === 'expanded'
      ? path.join(options.outputPath, scssParsedPath.name + '.css')
      : path.join(options.outputPath, scssParsedPath.name + '.min.css');

  const sourceMapOutputPath = options.sourceMap ? cssOutputPath + '.map' : null;
  const annotation = path.basename(cssOutputPath) + '.map';

  const postCssSourceMap = options.sourceMap
    ? { inline: false, prev: sassCompileResult.sourceMap, annotation }
    : undefined;

  const postCssResult = await postcss(postCssPlugins).process(sassCompileResult.css, {
    from: scssPath,
    to: cssOutputPath,
    map: postCssSourceMap,
  });

  postCssResult.warnings().forEach((warn) => {
    Logger.warning(warn.toString());
  });

  const header = `
/**
 * Do not edit directly
 * Generated by cocokits 'scss-builder'
 */
 
`;

  fs.writeFileSync(cssOutputPath, header + postCssResult.css);

  if (options.sourceMap) {
    fs.writeFileSync(sourceMapOutputPath, postCssResult.map.toString());
  }

  return {
    cssPath: cssOutputPath,
    sourceMapPath: sourceMapOutputPath,
  };
}
